/**
 * Domain model types shared across the entire backend.
 * All entities use a string `id` generated by the service layer (UUID v4).
 *
 * @author Shiri Rave
 * @since 09/06/26
 */
/**
 * Fixed duration of every auction window.
 * Spec: "Auction duration: 3 days".
 */
export const AUCTION_DURATION_DAYS = 3;
//# sourceMappingURL=types.js.map