/**
 * Domain model types shared across the entire backend.
 * All entities use a string `id` generated by the service layer (UUID v4).
 *
 * @author Shiri Rave
 * @since 09/06/26
 */

/**
 * The set of roles a user can hold in the system.
 * - ADMIN    – full access to all resources and users.
 * - MANAGER  – manages accounts assigned to them and opens auctions.
 * - USER     – creates events on related accounts.
 * - BANKER   – submits interest-rate offers for eligible auctions.
 */
export type Role = "ADMIN" | "MANAGER" | "USER" | "BANKER";

/**
 * Fixed duration of every auction window.
 * Spec: "Auction duration: 3 days".
 */
export const AUCTION_DURATION_DAYS = 3;

/**
 * Visibility / submission model for an auction.
 * SEALED means each bank submits one blind offer; the winner (lowest rate)
 * is revealed only when the auction closes.
 */
export type AuctionModel = "SEALED";

/** Lifecycle states an Account can be in. */
export type AccountStatus = "NEW" | "ELIGIBLE" | "AUCTION_OPEN" | "WON" | "EXPIRED";

/** The set of event types that can be recorded against an account. */
export type EventType =
  | "document_uploaded"
  | "status_changed"
  | "note_added"
  | "auction_opened"
  | "offer_submitted"
  | "auction_closed";

/**
 * A registered user of the platform.
 * `passwordHash` is stored server-side only and must never be sent to clients;
 * use {@link PublicUser} for outbound responses.
 */
export interface User {
  /** Unique identifier (UUID v4). */
  id: string;
  /** Display name. */
  name: string;
  /** Unique login email. */
  email: string;
  /** RBAC role assigned at registration. */
  role: Role;
  /** Bank affiliation — populated only for BANKER users. */
  bankId?: string;
  /** bcrypt hash of the user's password. Never serialised to clients. */
  passwordHash: string;
}

/** The client-safe projection of {@link User} with the password hash removed. */
export type PublicUser = Omit<User, "passwordHash">;

/**
 * A CRM account representing a customer relationship managed by the platform.
 *
 * Financial fields (`salary`, `loanAmount`, `propertyValue`) are visible to
 * BANKERs so they can price their interest-rate offers. Personal identity
 * fields (`customerName`, `phone`, `email`) are stripped before the account is
 * sent to a BANKER — see {@link stripAccountPII} in `rbac.ts`.
 */
export interface Account {
  /** Unique identifier (UUID v4). */
  id: string;
  /** Customer's full name. Stripped from banker-facing responses. */
  customerName: string;
  /** Contact phone number. Stripped from banker-facing responses. */
  phone: string;
  /** Customer email address. Stripped from banker-facing responses. */
  email: string;
  /** Current lifecycle status of the account. */
  status: AccountStatus;
  /** ID of the manager responsible for this account. */
  managerId: string;
  /** ISO-8601 timestamp of the last recorded activity, if any. */
  lastActivity?: string;
  /** True when the account has had more than 3 events in the past 24 hours. */
  highActivity: boolean;
  /** Customer's annual salary in the local currency (used for loan pricing). */
  salary?: number;
  /** Requested loan amount in the local currency. */
  loanAmount?: number;
  /** Appraised value of the property securing the loan. */
  propertyValue?: number;
}

/**
 * An activity event recorded against an account (e.g. a document upload or
 * a status change). Events are immutable once created.
 */
export interface Event {
  /** Unique identifier (UUID v4). */
  id: string;
  /** The account this event belongs to. */
  accountId: string;
  /** Category of the event. */
  type: EventType;
  /** Optional human-readable description. */
  description?: string;
  /** ID of the user who created this event. */
  createdByUserId: string;
  /** ISO-8601 creation timestamp. */
  createdAt: string;
}

/**
 * An open auction that allows eligible banks to submit interest-rate offers
 * for a specific customer account. Auctions run for {@link AUCTION_DURATION_DAYS}.
 */
export interface AuctionOpportunity {
  /** Unique identifier (UUID v4). */
  id: string;
  /** The account this auction was opened for. */
  accountId: string;
  /** Submission model — always SEALED in the current implementation. */
  model: AuctionModel;
  /** Current lifecycle status of the auction. */
  status: "OPEN" | "CLOSED" | "EXPIRED";
  /** IDs of banks permitted to submit offers for this auction. */
  eligibleBankIds: string[];
  /** ISO-8601 timestamp when the auction was opened. */
  openedAt: string;
  /** ISO-8601 timestamp when the auction window closes. */
  expiresAt: string;
  /** ID of the winning {@link BankOffer}, set when the auction closes with offers. */
  winningOfferId?: string;
}

/**
 * An interest-rate offer submitted by a bank for a specific auction.
 * In the SEALED model each bank may submit at most one offer per auction.
 */
export interface BankOffer {
  /** Unique identifier (UUID v4). */
  id: string;
  /** The auction this offer was submitted for. */
  auctionId: string;
  /** The submitting bank's identifier. */
  bankId: string;
  /** Annual interest rate offered (percentage). */
  interestRate: number;
  /** ISO-8601 submission timestamp. */
  createdAt: string;
}
